services:
  - type: web
    name: cjdquick-oms
    env: node
    region: singapore
    plan: free
    branch: main
    buildCommand: "npm install --legacy-peer-deps && cd apps/web && npm run build"
    startCommand: "cd apps/web && node_modules/.bin/next start -p $PORT"
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: AUTH_TRUST_HOST
        value: true
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: cjdquick-oms
          property: url
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
